### ISSUE TITLE
Erro install

### ISSUE THREAD

**Issue by 0x01882** [D4rkwat3r/ProjZ#2]
pip install projz.py
Collecting projz.py
  Using cached ProjZ.py-2.4.6.tar.gz (30 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [17 lines of output]
      Traceback (most recent call last):
        File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "/usr/local/lib/python3.7/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "/tmp/pip-build-env-rzp9bcn1/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "/tmp/pip-build-env-rzp9bcn1/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "/tmp/pip-build-env-rzp9bcn1/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-rzp9bcn1/overlay/lib/python3.7/site-packages/setuptools/build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 13, in <module>
      TypeError: 'type' object is not subscriptable
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

Python3+
Python3.7

**Comment by 0x01882** [comment]
I was able to fix it using python3.9

pip3.9 install projz.py
python3.9 main.py

**Comment by 0x01882** [comment]
Not sending messages

**Comment by AgielGomes** [comment]
same problem of not sending messages, all other functions like send qi or kick from chat works normally

**Comment by duckybrpy** [comment]
Yes, mine also has the same problem but the rest of the functions work

**Comment by D4rkwat3r** [comment]
I checked it and sending messages works fine. How do you call the send_message function? After an error, no exception is raised?

**Comment by duckybrpy** [comment]
It doesn't know any errors it just doesn't send anything, I pass the chat id and content in case the message 

await client.send_message(id_chat, content="test")

I have already tried using the example shown and it also does not send a message

**Comment by D4rkwat3r** [comment]
> It doesn't know any errors it just doesn't send anything, I pass the chat id and content in case the message
> 
> await client.send_message(id_chat, content="test")
> 
> I have already tried using the example shown and it also does not send a message

Update the library version to 2.4.7. If that doesn't help, try to enable websocket logging and let me know about the messages that will be output while sending the chat message.

`client = Client(ws_logging=True)`

**Comment by duckybrpy** [comment]
Ok

**Comment by duckybrpy** [comment]
I made a command for him to send me the message and it was not

[WS 2023-08-10 16:59:58] [INCOMING] [1] [1568 bytes]
[WS 2023-08-10 16:59:58] [INCOMING] [1] [1973 bytes]
[WS 2023-08-10 16:59:58] [INCOMING] [1] [1998 bytes]
[WS 2023-08-10 16:59:58] [INCOMING] [1] [1994 bytes]
[WS 2023-08-10 16:59:59] [INCOMING] [1] [2090 bytes]
[WS 2023-08-10 16:59:59] [INCOMING] [1] [1877 bytes]
[WS 2023-08-10 16:59:59] [INCOMING] [1] [1869 bytes]
[WS 2023-08-10 16:59:59] [INCOMING] [1] [2014 bytes]
[WS 2023-08-10 16:59:59] [INCOMING] [1] [1999 bytes]
[WS 2023-08-10 17:00:00] [INCOMING] [1] [1995 bytes]
[WS 2023-08-10 17:00:00] [INCOMING] [1] [1995 bytes]
[WS 2023-08-10 17:00:00] [INCOMING] [1] [1939 bytes]
[WS 2023-08-10 17:00:01] [OUTGOING] [8] [7 bytes]
[WS 2023-08-10 17:00:01] [INCOMING] [1] [1962 bytes]
[WS 2023-08-10 17:00:01] [INCOMING] [1] [2179 bytes]
[WS 2023-08-10 17:00:01] [INCOMING] [1] [1999 bytes]
[WS 2023-08-10 17:00:02] [INCOMING] [1] [1986 bytes]
[WS 2023-08-10 17:00:02] [INCOMING] [1] [1869 bytes]
[WS 2023-08-10 17:00:02] [INCOMING] [1] [1994 bytes]
[WS 2023-08-10 17:00:03] [INCOMING] [1] [151 bytes]
[WS 2023-08-10 17:00:03] [INCOMING] [1] [2061 bytes]
[WS 2023-08-10 17:00:04] [OUTGOING] [8] [7 bytes]
[WS 2023-08-10 17:00:04] [INCOMING] [1] [1869 bytes]
[WS 2023-08-10 17:00:04] [INCOMING] [1] [1995 bytes]
[WS 2023-08-10 17:00:04] [INCOMING] [1] [878 bytes]
[WS 2023-08-10 17:00:04] [INCOMING] [1] [1994 bytes]
[WS 2023-08-10 17:00:05] [INCOMING] [1] [1999 bytes]
[WS 2023-08-10 17:00:05] [INCOMING] [1] [2088 bytes]
1613375259357560086 command
[WS 2023-08-10 17:00:05] [OUTGOING] [1] [176 bytes]
[WS 2023-08-10 17:00:06] [INCOMING] [1] [1875 bytes]
[WS 2023-08-10 17:00:06] [INCOMING] [1] [1568 bytes]
[WS 2023-08-10 17:00:07] [OUTGOING] [8] [7 bytes]
[WS 2023-08-10 17:00:07] [INCOMING] [1] [1999 bytes]
[WS 2023-08-10 17:00:07] [INCOMING] [1] [1999 bytes]
[WS 2023-08-10 17:00:07] [INCOMING] [1] [1999 bytes]
[WS 2023-08-10 17:00:08] [INCOMING] [1] [154 bytes]
[WS 2023-08-10 17:00:08] [INCOMING] [1] [1666 bytes]
[WS 2023-08-10 17:00:09] [INCOMING] [1] [1999 bytes]
[WS 2023-08-10 17:00:09] [INCOMING] [1] [154 bytes]
[WS 2023-08-10 17:00:09] [INCOMING] [1] [2182 bytes]
[WS 2023-08-10 17:00:09] [INCOMING] [1] [298 bytes]
[WS 2023-08-10 17:00:10] [INCOMING] [1] [2014 bytes]
[WS 2023-08-10 17:00:10] [OUTGOING] [8] [7 bytes]
[WS 2023-08-10 17:00:10] [INCOMING] [1] [1771 bytes]

**Comment by duckybrpy** [comment]
I wonder if you are still going to update the library 🥺

**Comment by duckybrpy** [comment]
[HTTP 2023-09-07 03:55:47] [POST /v1/chat/threads/thread_id/members] [0 bytes]

**Comment by D4rkwat3r** [comment]
> I wonder if you are still going to update the library 🥺

Have you tried to send a message directly via the chat id which can be obtained through a link to the chat?
without @on_message.

**Comment by duckybrpy** [comment]
Yes, I already tried

**Comment by duckybrpy** [comment]
Hi dark, dark is there anything I can study so I can make a z library? I would like to continue with your repository and update
